# Assignment 1 - Numpy

In [7]:
#1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
vector = (np.arange(10) == 4).astype(int)
print(vector)

[0 0 0 0 1 0 0 0 0 0]


In [2]:
#2. Create a vector with values ranging from 10 to 49.
vector2 = np.arange(10,50)
print(vector2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
vector3 = np.arange(9).reshape(3,3)
print(vector3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [27]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
ary = np.nonzero([1,2,0,0,4,0])
print(ary)

(array([0, 1, 4], dtype=int64),)


In [32]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
ary1 = np.random.random((10,10))
print(ary1)
print("Maximum value: ", ary1.max())
print("Minimum value: ", ary1.min())

[[6.70010089e-01 5.84440767e-01 4.10024995e-01 7.80948212e-01
  1.48732788e-01 2.19785755e-01 4.39157044e-01 7.13586306e-01
  5.70983810e-01 7.96404392e-01]
 [6.18508355e-02 6.67341718e-01 1.98456111e-01 3.12088455e-01
  7.60304973e-01 5.12186914e-01 3.40477885e-01 2.73156641e-01
  4.36988619e-01 6.81284868e-04]
 [8.45795118e-01 9.99762495e-01 9.57201066e-01 9.80126697e-01
  7.91361570e-01 4.60102423e-01 8.03871514e-01 9.13500906e-01
  8.43679051e-01 9.61042982e-01]
 [3.15406326e-01 8.61643210e-01 5.33444124e-01 5.03805076e-02
  6.83655565e-02 7.36396712e-01 1.21626569e-01 1.11488640e-01
  4.97353376e-01 3.52669092e-03]
 [6.83775402e-01 4.74089200e-01 4.42614334e-01 4.59760244e-01
  5.63825063e-01 6.26329734e-01 9.29927815e-02 2.23467262e-01
  6.32751296e-01 8.43240934e-01]
 [7.18823785e-01 1.80671777e-01 6.07116369e-02 1.68638422e-01
  6.67819956e-01 8.90758594e-01 9.34049837e-01 6.13295618e-01
  5.94297870e-01 4.26564149e-01]
 [3.92933556e-01 5.19605144e-02 9.93319311e-01 8.62234018e

In [30]:
#6. Create a random vector of size 30 and find the mean value.
ary2 = np.random.random(30)
print(ary2)
print("Mean: ",ary2.mean())

[0.11804985 0.63876927 0.7157665  0.92134368 0.42014557 0.65167842
 0.27026878 0.22790591 0.68115227 0.49519532 0.11240736 0.70566575
 0.97674648 0.23528369 0.5241824  0.5651007  0.60011186 0.53953821
 0.27187951 0.08937604 0.00319569 0.35386038 0.47061349 0.04377897
 0.52634164 0.61608396 0.216838   0.02491343 0.48587634 0.89734547]
Mean:  0.4466471641304654
